#!/usr/bin/env bash
# This script is for set a several variables into env.

export HBNB_MYSQL_USER="hbnb_dev"
export | grep HBNB_MYSQL_USER
export HBNB_MYSQL_PWD="hbnb_dev_pwd"
export | grep HBNB_MYSQL_PWD
export HBNB_MYSQL_HOST="localhost"
export | grep HBNB_MYSQL_HOST
export HBNB_MYSQL_DB="hbnb_dev_db"
export | grep HBNB_MYSQL_DB
export HBNB_TYPE_STORAGE="db"
export | grep HBNB_TYPE_STORAGE
